server:
  port: 8081
spring:
  application:
    name: loans
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/ms-loans-db
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  config:
    import: optional:configserver:http://localhost:8070/
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# Info for eureka-server microservice registration
info:
  app:
    name: "loans"
    description: "MS Bank Loans rest service"
    version: "1.0.0"
